### ISSUE TITLE
RF: Support PostgreSQL database

### ISSUE THREAD

**Issue by Nek-12** [janbarari/gradle-analytics-plugin#130]
Currently gradle analytics supports mysql or sqlite only.
A lot of companies & developers are using porgresql already, so support for it should be provided

**Comment by Nek-12** [comment]
Currently I observe that the plugin simply hangs the build after the compilation is done

**Comment by janbarari** [comment]
Hey @Nek-12 
Thanks for submitting the feature request and your feedback. regarding to hangs that may happen because of the connection between your computer and the MySQL server. but I will check it whenever I can. At first, I planned to support the plugin fast and thought the users would support me by donating, but after creating this plugin with lots of features, in the last year, no one donated even a single dollar. It's become hard for me to develop this project fast enough because I am working hard for my employer to support my life. Anyway, thanks for submitting your feedback, I will add a note to consider your issue.

**Comment by janbarari** [comment]
Support for PostgreSQL database has been added to the plugin, it will be accessible in the next version soon.
Thanks for your feedback. 
Put a smile on my face by [donating](https://janbarari.github.io/gradle-analytics-plugin/donation/) to the project.

<img width="396" alt="Screenshot 2024-01-20 at 5 41 03 PM" src="https://github.com/janbarari/gradle-analytics-plugin/assets/12547060/61623596-411e-42aa-b4a9-938bbac49a0d">

**Comment by Nek-12** [comment]
>  At first, I planned to support the plugin fast and thought the users would support me by donating, but after creating this plugin with lots of features, in the last year, no one donated even a single dollar. It's become hard for me to develop this project fast enough because I am working hard for my employer to support my life. Anyway, thanks for submitting your feedback, I will add a note to consider your issue.

Hello. Regarding this, I wouldn't expect you to receive many donations when the repository has just about 100 stars. I'd think donations should start when you reach about 1000 to 3000 stars. I think you can work on popularizing the plugin by writing a good selling readme, SEO, writing articles, attending tech conferences and promoting it there, promoting it on twitter. But I don't think you'll ever be able to work on open-source projects full-time unless you develop an industry-wide standard framework (like RxJava or Koin for example). Hey, I don't even see a CTA to buy you a coffee in the github repo! You also do not support anything except crypto and crypto is banned in my country. Think about how you can make donations easier.

Regarding the feature, thanks a lot, can you release it anywhere soon?

**Comment by janbarari** [comment]
It probably will be released on 10th Feb 2024

**Comment by janbarari** [comment]
You can use the earlier version before the official release
`plugins {
  id("io.github.janbarari.gradle-analytics-plugin") version "1.0.2-pre1"
}`

**Comment by janbarari** [comment]
Thank you so much for helping me to improve the plugin functionalities. Your submitted issues, request features, and bug reports mean a lot to me ❤️
