### ISSUE TITLE
Feature: Enable/Disable

### ISSUE THREAD

**Issue by bellini-ea** [janbarari/gradle-analytics-plugin#45]
Plugin is great, so thanks for putting this out.

I'm thinking that I want to have this run for me locally (configured by a gradle.properties value) but not for the rest of my team at this point.  Be nice to have a way to enable / disable the plugin so it doesn't do anything such as the summary unless its enabled (i.e. it can be configured, but won't run)

**Comment by janbarari** [comment]
Hey @bellini-ea, Thank you for sending me the feedback.
Hmm. I will put this feature in the upcoming release which you can enable/disable the plugin from your local `gradle.properties` file.

**Comment by janbarari** [comment]
Feature added in version `1.0.0-beta4`. Stay up to date to get the release soon.

**Comment by janbarari** [comment]
Hey @bellini-ea 
The new version `1.0.0-beta4` is available 🎊 
Thank you for helping me improve the plugin 🧡

**Comment by bellini-ea** [comment]
Thanks. Tried beta4 and set the configuration for isEnabled=false where it would get applied to modules in my project, I see it running still.

```
> Task app1:reportAnalytics

 ??????????????????????????????????????????????????????????????????????
 ? Gradle Analytics Plugin                                            ?
 ?--------------------------------------------------------------------?
 ? There is no data to process. Please check the plugin configuration ?
 ? and wait until the first desired task information is saved.        ?
 ??????????????????????????????????????????????????????????????????????

> Task :app2:reportAnalytics

 ??????????????????????????????????????????????????????????????????????
 ? Gradle Analytics Plugin                                            ?
 ?--------------------------------------------------------------------?
 ? There is no data to process. Please check the plugin configuration ?
 ? and wait until the first desired task information is saved.        ?
 ??????????????????????????????????????????????????????????????????????

```
My configuration looks like this:
```
gradleAnalyticsPlugin {
        isEnabled = false
...
```
Whats the expected behavior you anticipated?

**Comment by janbarari** [comment]
Hey @bellini-ea 
You executed `reportAnalytics` task. This is the plugin getting report task. This functionality keeps working in all situations. because it is not a part of your project build workflow.
The `isEnabled` flag won't let the plugin run analyze, save and print data once Gradle has built your requested tasks.

**Comment by janbarari** [comment]
by the way, a HotFix is available. so please use version `1.0.0-beta5`. but this functionality is the same.
