### ISSUE TITLE
Feedback: Aggregate Reporting

### ISSUE THREAD

**Issue by bellini-ea** [janbarari/gradle-analytics-plugin#50]
In a multi-module project, the plugin reports for each subproject.  An option for only the aggregate reports seem reasonable give we would be interested in the overall build rather than each submodule build.

**Comment by janbarari** [comment]
Hey @bellini-ea 
Thanks for submitting the feedback.
The overall build already exists but having sub-project build information also would help to find the bottlenecks in large projects, it will help to see which subprojects consume more time, and more compile process. It is a good metric to detect when It's needed to break a sub-project into

**Comment by bellini-ea** [comment]
I see. I think because I saw each report summary print at the end of each build.  Maybe it would be good to turn that off and make it an option to print for each submodule or something like that?  The block that prints the link to the report in the ????? box.

**Comment by janbarari** [comment]
> The block that prints the link to the report in the ????? box.

⬆️  Is this show at the end of each build for you?
Can you show by a snapshot?

**Comment by janbarari** [comment]
I close the conversation since there is no active conversation. Feel free to open it if the issue is not resolved for you.
