### ISSUE TITLE
RF: Exclude some modules from Modules Dependency Graph

### ISSUE THREAD

**Issue by haizerdev** [janbarari/gradle-analytics-plugin#81]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/46586567/206442806-672ae4ee-cd45-4f7a-bd87-6e7bafeb55d7.png">

**Comment by janbarari** [comment]
Hey @haizerdev 
Can you give me a detailed brief about this?

Thanks

**Comment by janbarari** [comment]
Hi @haizerdev 
Thank you for reporting this request feature
Actually, I think this is safe and useful to have excluded module option inside the plugin configuration. But. I have a question, Would you like to have this only in the graph or all metrics?

**Comment by haizerdev** [comment]
I think it will be enough to exclude the module everywhere, and then we can get 2 different graphs for two different configurations in the project (that is, for two different app modules)

**Comment by janbarari** [comment]
Due to misunderstandings among users, The second option is a bit risky to have two different graphs with one configuration.
But the exclude option for everywhere is kind of possible, I need to make sure it won't break the report accuracy.

**Comment by ilkupi** [comment]
AlsoI have similar request. In our project we have some test application modules, that are not build during regular CI run, and so Cache Hit Diagrame is kinda useless.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/93395694/215767079-2b513b46-20c8-44b9-a172-e8570ddf9615.png">

**Comment by janbarari** [comment]
> Also I have similar request. In our project we have some test application modules, that are not build during regular CI run, and so Cache Hit Diagrame is kinda useless. <img alt="image" width="502" src="https://user-images.githubusercontent.com/93395694/215767079-2b513b46-20c8-44b9-a172-e8570ddf9615.png">

Hmm. Thanks sharing this :)

**Comment by janbarari** [comment]
Added in Milestone `1.0.0-beta8`.
cc: @ilkupi @haizerdev

**Comment by janbarari** [comment]
I have published the latest plugin version `1.0.0-beta8` which includes the feature you reported. Thank you for bringing it to my attention! :)

cc: @ilkupi @haizerdev
