### ISSUE TITLE
RB: Modules Source Count/Modules Source Size/Modules Method Count not calculate 

### ISSUE THREAD

**Issue by haizerdev** [janbarari/gradle-analytics-plugin#82]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/46586567/208089106-39efc0d1-7558-4bae-add4-a44e3e40252f.png">

**Comment by janbarari** [comment]
Hi @haizerdev 
Thanks for submitting the issue.
I think a bug report is required for plugin. Currently there isn't any logger to send me. So I need to get more information from you to reproduce this issue.

Can you tell me how you reproduce this issue?

**Comment by janbarari** [comment]
I couldn't reproduce this issue. If it happened again. Use upcoming `v1.0.0-beta6` which has an internal logger. Then It would be easier for me to reproduce it :)
