### ISSUE TITLE
Feedback: How should I open report file?

### ISSUE THREAD

**Issue by nassdk** [janbarari/gradle-analytics-plugin#87]
Hey, great idea and solution. Thank you for that plugin! Can you explain to me how I should open the report .db file to see all diagrams, etc.? I don't get it actually :( Or maybe I misunderstood something.

**Comment by janbarari** [comment]
Hey @nassdk 
Thank you for the energy you gave me 🙏🏼
You don't need to open the database file. follow the [Getting Report](https://janbarari.github.io/gradle-analytics-plugin/getting-report/) to generate report.

**Comment by nassdk** [comment]
Oh, yeah, I got it. Thank you, I'm closing issue.
