### ISSUE TITLE
RB: Stats do not collected on Gitlab CI

### ISSUE THREAD

**Issue by ilkupi** [janbarari/gradle-analytics-plugin#88]
Hello. Super useful plugin, thanks!

However, I can't figure out why it isn't recording stats on the Gitlab CI. When script calls `./gradlew reportAnalytics` after a successful build, it outputs empty result. Locally it is totally working. I've checked .db file on CI - it was empty.

Here is build.gradle section:
```
gradleAnalyticsPlugin {
    enabled = true

    database {
        local = sqlite {
            path = "$rootDir/plugins/gradleAnalytics/"
            name = 'gradleAnalyticsPlugin' // Don't add `.db` in the database name.
        }
        ci = sqlite {
            path = System.getenv("GRADLE_ANALYTICS_DB_PATH")
            name = 'gradleAnalyticsPlugin' // Don't add `.db` in the database name.
        }
    }

    trackingTasks = [
            // Add your requested tasks to be analyzed, Example:
            ':app:assembleDebug'
    ]

    trackingBranches = [
            'dev',
            "ANDR-4827_dependency_graph_analysis"
    ]

//    outputPath = "OUTPUT_REPORT_PATH"
}
```

**Comment by ilkupi** [comment]
Probably, issue in that GITLAB creates a shallow copy of repository, where branches are not present so it checkouts a commit, not a branch: https://forum.gitlab.com/t/gitlab-runner-13-1-1-checks-out-a-commit-and-not-my-branch/39996
However suggested fix from there to set `GIT_DEPTH=0` didn't work out for me.
So I added this monstrosity to a gitlab job script to test if it would work for locally created branch with same name as I need:
```
  script:
    - if [[ `git rev-parse --abbrev-ref HEAD` == "HEAD" ]]; then
      git branch $CI_COMMIT_REF_NAME &&
      git checkout $CI_COMMIT_REF_NAME &&
      echo "created local branch $CI_COMMIT_REF_NAME";
      fi
    - ./gradlew :app:assembleDebug
```
And it worked, DB was filled and report was successfully created

**Comment by ilkupi** [comment]
@janbarari could you add check for an environmental variable that contains branch name in addition to current git branch check?

**Comment by BarsukovNik** [comment]
I have the same issue, do you have any results?

**Comment by janbarari** [comment]
Hey @ilkupi & @BarsukovNik 
I will investigate it tomorrow :)

**Comment by janbarari** [comment]
> @janbarari could you add check for an environmental variable that contains branch name in addition to current git branch check?

Sorry for the delay. I am actively working on it.

**Comment by janbarari** [comment]
> Probably, issue in that GITLAB creates a shallow copy of repository, where branches are not present so it checkouts a commit, not a branch: https://forum.gitlab.com/t/gitlab-runner-13-1-1-checks-out-a-commit-and-not-my-branch/39996 However suggested fix from there to set `GIT_DEPTH=0` didn't work out for me. So I added this monstrosity to a gitlab job script to test if it would work for locally created branch with same name as I need:
> 
> ```
>   script:
>     - if [[ `git rev-parse --abbrev-ref HEAD` == "HEAD" ]]; then
>       git branch $CI_COMMIT_REF_NAME &&
>       git checkout $CI_COMMIT_REF_NAME &&
>       echo "created local branch $CI_COMMIT_REF_NAME";
>       fi
>     - ./gradlew :app:assembleDebug
> ```
> 
> And it worked, DB was filled and report was successfully created

Gitlab Solution ✅
