### ISSUE TITLE
RB: Statistics do not have an upgrade path through versions

### ISSUE THREAD

**Issue by pikzen** [janbarari/gradle-analytics-plugin#90]
Hi! I have a database with 400+ build logs, built with alpha02. It's also built on a relatively big project wit 200+ modules, so I'd gain lots from some of the recent fixes (like the mermaid graph straight up not existing for our project in earlier releases). Unfortunately, starting from alpha04, BuildMetric has a new field called modules, which causes every report & build later on to simply fail with `Required value 'modules' missing at $` (called from `DatabaseRepositoryImp`).

Is that new field absolutely critical for further operations and requires a database cleanup, or could the plugin add a migration for it ?

**Comment by janbarari** [comment]
Hey @pikzen 
Thanks for reporting this issue
I put this on my priority. I will let you know about that :)

**Comment by janbarari** [comment]
This issue was resolved in milestone `1.0.0-beta6` and the new version will be released in 1-2 weeks.
Thank you so much for the bug report 🙂
